[package]
name = "signer"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
libc = "0.2"
ethkey = { git = "https://github.com/ethcore/parity" }

[lib]
name = "signer"
crate-type = ["staticlib"]
